apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cratedb-pvc
  namespace: cratedb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard  # Use your cluster's storage class name